// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"wind-agent/internal/config"
	"wind-agent/internal/data"
)

// Injectors from wire.go:

func InitApp(cfgPath string) (*Application, func(), error) {
	app, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	dataData, err := data.NewData(app)
	if err != nil {
		return nil, nil, err
	}
	application, err := New(app, dataData)
	if err != nil {
		return nil, nil, err
	}
	return application, func() {
	}, nil
}
